version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: addressbook
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  addressbook:
    build:
      context: .
      dockerfile: Dockerfile
    image: addressbook:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/addressbook
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Root@123

volumes:
  mysql-data:
